match = {
    id: "{ID}",
    difference: "{DIF_RANK}",
    team1: {
        win: "{WIN0}",
        rank: "{TEAM_RANK1}",
        assault: {
            lvl: "{LVL1}",
            lvl_op: "{LVL_OP1}",
            rank: "{RANK1}",
            oper: "{OPER1}",
            group: "{GROUP1}",
            perks: "{PERK__1}",
            name: "{NAME1}",
            dmg: "{DMG1}",
            kills: "{KILLS1}",
            deaths: "{DEATHS1}",
            assists: "{ASSISTS1}",
            recive: "{RECIVE1}"
        },
        gunner: {
            lvl: "{LVL2}",
            lvl_op: "{LVL_OP2}",
            rank: "{RANK2}",
            oper: "{OPER2}",
            group: "{GROUP2}",
            perks: "{PERK__2}",
            name: "{NAME2}",
            dmg: "{DMG2}",
            kills: "{KILLS2}",
            deaths: "{DEATHS2}",
            assists: "{ASSISTS2}",
            recive: "{RECIVE2}"
        },
        medic: {
            lvl: "{LVL3}",
            lvl_op: "{LVL_OP3}",
            rank: "{RANK3}",
            oper: "{OPER3}",
            group: "{GROUP3}",
            perks: "{PERK__3}",
            name: "{NAME3}",
            dmg: "{DMG3}",
            kills: "{KILLS3}",
            deaths: "{DEATHS3}",
            assists: "{ASSISTS3}",
            recive: "{RECIVE3}"
        },
        sniper: {
            lvl: "{LVL4}",
            lvl_op: "{LVL_OP4}",
            rank: "{RANK4}",
            oper: "{OPER4}",
            group: "{GROUP4}",
            perks: "{PERK__4}",
            name: "{NAME4}",
            dmg: "{DMG4}",
            kills: "{KILLS4}",
            deaths: "{DEATHS4}",
            assists: "{ASSISTS4}",
            recive: "{RECIVE4}"
        },
    },
    team2: {
        win: "{WIN1}",
        rank: "{TEAM_RANK1}",
        assault: {
            lvl: "{LVL5}",
            lvl_op: "{LVL_OP5}",
            rank: "{RANK5}",
            oper: "{OPER5}",
            group: "{GROUP5}",
            perks: "{PERK__5}",
            name: "{NAME5}",
            dmg: "{DMG5}",
            kills: "{KILLS5}",
            deaths: "{DEATHS5}",
            assists: "{ASSISTS5}",
            recive: "{RECIVE5}"
        },
        gunner: {
            lvl: "{LVL6}",
            lvl_op: "{LVL_OP6}",
            rank: "{RANK6}",
            oper: "{OPER6}",
            group: "{GROUP6}",
            perks: "{PERK__6}",
            name: "{NAME6}",
            dmg: "{DMG6}",
            kills: "{KILLS6}",
            deaths: "{DEATHS6}",
            assists: "{ASSISTS6}",
            recive: "{RECIVE6}"
        },
        medic: {
            lvl: "{LVL7}",
            lvl_op: "{LVL_OP7}",
            rank: "{RANK7}",
            oper: "{OPER7}",
            group: "{GROUP7}",
            perks: "{PERK__7}",
            name: "{NAME7}",
            dmg: "{DMG7}",
            kills: "{KILLS7}",
            deaths: "{DEATHS7}",
            assists: "{ASSISTS7}",
            recive: "{RECIVE7}"
        },
        sniper: {
            lvl: "{LVL8}",
            lvl_op: "{LVL_OP8}",
            rank: "{RANK8}",
            oper: "{OPER8}",
            group: "{GROUP8}",
            perks: "{PERK__8}",
            name: "{NAME8}",
            dmg: "{DMG8}",
            kills: "{KILLS8}",
            deaths: "{DEATHS8}",
            assists: "{ASSISTS8}",
            recive: "{RECIVE8}"
        },
    },
};



export let match = match;